# Generated by Django 5.2 on 2025-07-15 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegulatoryBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('website', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegulatoryDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('act', 'Act'), ('regulation', 'Regulation'), ('directive', 'Directive'), ('guideline', 'Guideline'), ('form', 'Form')], max_length=20)),
                ('upload', models.FileField(upload_to='documents/')),
                ('description', models.TextField(blank=True)),
                ('published_date', models.DateField()),
                ('regulatory_body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regulations.regulatorybody')),
            ],
        ),
    ]
